<a href="https://colab.research.google.com/github/AdityaNerpagar/CV/blob/main/Combining_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# !unzip /content/drive/MyDrive/googlenet-models.zip -d data_dir

In [ ]:
# !unzip /content/drive/MyDrive/Vgg16-models.zip -d data_dir  #vgg16

In [ ]:
!unzip /content/drive/MyDrive/AGnet-models.zip -d data_dir  #vgg16

Archive:  /content/drive/MyDrive/AGnet-models.zip
   creating: data_dir/AGnet-models/
  inflating: data_dir/AGnet-models/Vgg19netModel4.h5  
  inflating: data_dir/AGnet-models/googlenetModelTHNB.h5  
  inflating: data_dir/AGnet-models/AlexnetModel.h5  
  inflating: data_dir/AGnet-models/resnet50Model1.h5  


In [ ]:
 #resnet
 pathResnet="/content/data_dir/AGnet-models/resnet50Model1.h5"

In [ ]:
#vgg19

pathVgg19="/content/data_dir/AGnet-models/Vgg19netModel4.h5"

In [ ]:
#alexnet
# !unzip /content/drive/MyDrive/AGenet-models.zip -d data_dir

In [ ]:
from keras.models import load_model

path1 = "/content/data_dir/AGnet-models/googlenetModelTHNB.h5"
path2 = "./data_dir/AGnet-models/AlexnetModel.h5"
path3 = "/content/drive/MyDrive/Vgg16netModel4.h5"
path4 = pathVgg19
path5 = pathResnet

# identical to the previous one
model_1 = load_model(path1)
model_2 = load_model(path2)
model_3 = load_model(path3)
model_4 = load_model(path4)
model_5 = load_model(path5)


In [ ]:
members=[model_1,model_2,model_3,model_4,model_5]

In [ ]:
model_1.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv2d (Conv2D)                (None, 112, 112, 64  9472        ['input_1[0][0]']                
                                )                                                                 
                                                                                                  
 max_pooling2d (MaxPooling2D)   (None, 56, 56, 64)   0           ['conv2d[0][0]']                 
                                                                                              

In [ ]:
model_2.summary()

Model: "AlexNet"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 conv0 (Conv2D)              (None, 54, 54, 96)        34944     
                                                                 
 bn0 (BatchNormalization)    (None, 54, 54, 96)        384       
                                                                 
 activation (Activation)     (None, 54, 54, 96)        0         
                                                                 
 max0 (MaxPooling2D)         (None, 26, 26, 96)        0         
                                                                 
 conv1 (Conv2D)              (None, 26, 26, 256)       614656    
                                                                 
 bn1 (BatchNormalization)    (None, 26, 26, 256)       1024

In [ ]:
model_4.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 tf.__operators__.getitem (S  (None, 224, 224, 3)      0         
 licingOpLambda)                                                 
                                                                 
 tf.nn.bias_add (TFOpLambda)  (None, 224, 224, 3)      0         
                                                                 
 vgg19 (Functional)          (None, 7, 7, 512)         20024384  
                                                                 
 global_average_pooling2d (G  (None, 512)              0         
 lobalAveragePooling2D)                                          
                                                                 
 dropout (Dropout)           (None, 512)               0     

In [ ]:
model_5.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 zero_padding2d_1 (ZeroPadding2  (None, 230, 230, 3)  0          ['input_2[0][0]']                
 D)                                                                                               
                                                                                                  
 conv1 (Conv2D)                 (None, 112, 112, 64  9472        ['zero_padding2d_1[0][0]']       
                                )                                                           

In [ ]:
!unzip drive/MyDrive/THNB.zip -d data_dir

Streaming output truncated to the last 5000 lines.
  inflating: data_dir/THNB/T/vishal435.jpg  
  inflating: data_dir/THNB/T/vishal440.jpg  
  inflating: data_dir/THNB/T/vishal445.jpg  
  inflating: data_dir/THNB/T/vishal450.jpg  
  inflating: data_dir/THNB/T/vishal455.jpg  
  inflating: data_dir/THNB/T/vishal460.jpg  
  inflating: data_dir/THNB/T/vishal465.jpg  
  inflating: data_dir/THNB/T/vishal470.jpg  
  inflating: data_dir/THNB/T/vishal475.jpg  
  inflating: data_dir/THNB/T/vishal480.jpg  
  inflating: data_dir/THNB/T/vishal485.jpg  
  inflating: data_dir/THNB/T/vishal490.jpg  
  inflating: data_dir/THNB/T/vishal495.jpg  
  inflating: data_dir/THNB/T/vishal500.jpg  
  inflating: data_dir/THNB/T/vishal505.jpg  
  inflating: data_dir/THNB/T/vishal510.jpg  
  inflating: data_dir/THNB/T/vishal515.jpg  
  inflating: data_dir/THNB/T/vishal520.jpg  
  inflating: data_dir/THNB/T/vishal525.jpg  
  inflating: data_dir/THNB/T/vishal530.jpg  
  inflating: data_dir/THNB/T/vishal535.jpg  
  in

In [ ]:
!pip install split-folders
import splitfolders
ipf = "./data_dir/THNB"
opf = './data_dir/split'

splitfolders.ratio(ipf,output =opf,seed = 42,ratio=(.8, .1, .1))

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Copying files: 27893 files [00:23, 1182.33 files/s]


In [ ]:
import shutil
import os
import numpy as np
import argparse

def get_files_from_folder(path):

    files = os.listdir(path)
    return np.asarray(files)

def main(path_to_data, path_to_test_data, train_ratio):
    # get dirs
    _, dirs, _ = next(os.walk(path_to_data))

    # calculates how many train data per class
    data_counter_per_class = np.zeros((len(dirs)))
    for i in range(len(dirs)):
        path = os.path.join(path_to_data, dirs[i])
        files = get_files_from_folder(path)
        data_counter_per_class[i] = len(files)
    test_counter = np.round(data_counter_per_class * (1 - train_ratio))

    # transfers files
    for i in range(len(dirs)):
        path_to_original = os.path.join(path_to_data, dirs[i])
        path_to_save = os.path.join(path_to_test_data, dirs[i])

        #creates dir
        if not os.path.exists(path_to_save):
            os.makedirs(path_to_save)
        files = get_files_from_folder(path_to_original)
        # moves data
        for j in range(int(test_counter[i])):
            dst = os.path.join(path_to_save, files[j])
            src = os.path.join(path_to_original, files[j])
            shutil.move(src, dst)


def parse_args():
  parser = argparse.ArgumentParser(description="Dataset divider")
  parser.add_argument("--data_path", required=True,
    help="Path to data")
  parser.add_argument("--test_data_path_to_save", required=True,
    help="Path to test data where to save")
  parser.add_argument("--train_ratio", required=True,
    help="Train ratio - 0.7 means splitting data in 70 % train and 30 % test")
  return parser.parse_args()

if __name__ == "__main__":
  args = parse_args()
  main(args.data_path, args.test_data_path_to_save, float(args.train_ratio))

In [ ]:
from PIL import Image
# from tensorflow.keras.preprocessing.image import ImageDataGenerator

# BATCH_SIZE = 16
# EPOCH_STEPS = int(4323/BATCH_SIZE)
# IMAGE_SHAPE = (224, 224, 3)
# paths = ["./data_dir/cluster2/OHNB", 
#  "./data_dir/cluster2/THNB", # Change to the path of the directory containing the files you want to rename
#  "./data_dir/cluster2/OHNH", # Change to the path of the directory containing the files you want to rename
#  "./data_dir/cluster2/THNH", # Change to the path of the directory containing the files you want to rename
#  "./data_dir/cluster2/THNHB" ]# Change to the path of the directory containing the files you want to rename

# train_datagen = ImageDataGenerator(
#     rescale=1./255,
#     #rotation_range=30,
#     width_shift_range=0.2,
#     height_shift_range=0.2,
#     shear_range=0.2,
#     zoom_range=0.2,
#     horizontal_flip=True
# )

# IMAGE_TRAIN = paths[0]
# generator_thnh = train_datagen.flow_from_directory(
#     IMAGE_TRAIN,
#     target_size=(IMAGE_SHAPE[0], IMAGE_SHAPE[1]),
#     batch_size=BATCH_SIZE,
#     class_mode='categorical'
# )

# image = Image.open('./data_dir/cluster2/THNHB/lion/95.png')
# new_image = image.resize((224,224))
# model_1.predict(new_image)

In [ ]:
# from tensorflow.keras.preprocessing import image
# from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
# import numpy as np
# import cv2
# import matplotlib.pyplot as pl


# img_path = "./data_dir/cluster2/THNHB/lion/95.png"
# # img = image.load_img(img_path, target_size=(224, 224,3))
# img2 = cv2.imread(img_path)
# resized = cv2.resize(img2,(224,224))
# numpy.expand_dims(data, axis=0)
# # img_array = image.img_to_array(img)
# # img_batch = np.expand_dims(img_array, axis=0)
# # img_preprocessed = preprocess_input(img_batch)
# prediction = model_1.predict(resized)

# # print(decode_predictions(prediction))

In [ ]:
import numpy as np
import cv2
import os
import matplotlib.pyplot as pl
import random

# ipf = "./data_dir/THNB"
# d=""
# for classes in os.listdir(ipf):
#   files=os.listdir(os.path.join(ipf,classes))
#   d=random.choice(files)

# # img_path = "/content/data_dir/split/test/D/agrima130.jpg"
# # # img = image.load_img(img_path, target_size=(224, 224,3))
# # img2 = cv2.imread(img_path)
# # resized = cv2.resize(img2,(224,224))
# # testdata1=np.array(resized)
# # # testdata1 = testdata1.astype('float32')
# # testdata1= np.reshape(testdata1,[1,224,224,3] )

#   img_path =d
# # img = image.load_img(img_path, target_size=(224, 224,3))
#   img2 = cv2.imread(img_path)
#   resized = cv2.resize(img2,(224,224))
#   testdata1=np.array(resized)
# # testdata1 = testdata1.astype('float32')
#   testdata1= np.reshape(testdata1,[1,224,224,3] )


# np.expand_dims(testdata1, axis=0)
# img_array = image.img_to_array(img)
# img_batch = np.expand_dims(img_array, axis=0)
# img_preprocessed = preprocess_input(img_batch)
# img = image.load_img(img_path, target_size=(224, 224,3))

# for imgs in img_path:
#   img = cv2.imread(imgs)
#   resized = cv2.resize(img,(224,224))
#   testdata1=np.array(resized)
#   testdata1= np.reshape(testdata1,[1,224,224,3] )
  
# # np.expand_dims(testdata1, axis=0)
# print(decode_predictions(prediction))

#One image Multiple models


In [ ]:
import math

In [ ]:
from operator import add
# list(map(add, test_list1, test_list2))

In [ ]:
enumList = {0: 'A',
 1: 'B',
 2: 'D',
 3: 'E',
 4: 'F',
 5: 'G',
 6: 'H',
 7: 'J',
 8: 'K',
 9: 'L',
 10: 'M',
 11: 'N',
 12: 'P',
 13: 'Q',
 14: 'R',
 15: 'S',
 16: 'T',
 17: 'V',
 18: 'W',
 19: 'X',
 20: 'Y',
 21: 'Z',
 22: 'accept',
 23: 'assistant',
 24: 'bag',
 25: 'book',
 26: 'cash',
 27: 'crocodile',
 28: 'dog',
 29: 'dupatta',
 30: 'fast',
 31: 'fish',
 32: 'help',
 33: 'home',
 34: 'horse',
 35: 'human',
 36: 'jeans',
 37: 'keep',
 38: 'laptop',
 39: 'location',
 40: 'meet',
 41: 'monkey',
 42: 'namastey',
 43: 'proof',
 44: 'shoot',
 45: 'signature',
 46: 'spider',
 47: 'stand',
 48: 'technology',
 49: 'tiger',
 50: 'tv',
 51: 'umbrella'}

In [ ]:
from PIL import Image
def ensemble_predictions(members, testX):
  individual_pred=[]
  tot=[]
 # make predictions
  for model in members:
    model_curr=model.predict(testX)
    preds=list(model_curr[0])

    if members.index(model)==0:
      # tot+=model_curr[0][0]
      tot= model_curr[0][0]
      # print("for google net",tot)
      #max(max(prediction[0])))
        


    else:
      tot=list(map(add, tot, preds))
      # print("other models",tot)

    # preds=list(model_curr[0])
    # print(preds)
    # print(max(preds))
    # individual_pred.append(preds.index(max(preds)))
  max_val=max(tot)  
  # print("max len: ",max_val)
  # print("len: ",len(tot))
  print("tot index for max value: ",tot.index(max_val))
  # individual_pred=np.array(individual_pred)
  # summed = np.sum(individual_pred, axis=0)
  # print(individual_pred)
  # argmax across classes
  result = enumList[tot.index(max_val)]
  return result





ipf = "./data_dir/THNB"
acc=0
l_final=[]
for classes in os.listdir(ipf):
  folderpath = os.path.join(ipf,classes)
  files=os.listdir(folderpath)
  d=random.choice(files)

# img_path = "/content/data_dir/split/test/D/agrima130.jpg"
# # img = image.load_img(img_path, target_size=(224, 224,3))
# img2 = cv2.imread(img_path)
# resized = cv2.resize(img2,(224,224))
# testdata1=np.array(resized)
# # testdata1 = testdata1.astype('float32')
# testdata1= np.reshape(testdata1,[1,224,224,3] )
  # print("files",files)
  img_path = os.path.join(folderpath,d)
  print(img_path)
  # img = Image.load_img(img_path, target_size=(224, 224,3))
  img2 = cv2.imread(img_path)
  resized = cv2.resize(img2,(224,224))
  testdata1=np.array(resized)
# testdata1 = testdata1.astype('float32')
  testdata1= np.reshape(testdata1,[1,224,224,3] )
  out = ensemble_predictions(members,testdata1)
  if classes==out:
    acc+=1
    l_final.append(out)

  else:
    l_final.append('wrong class classified: {}'.format(classes))  


  print(out)
print(l_final)
print(acc)

./data_dir/THNB/namastey/shruti375.jpg
1/1 [==============================] - 0s 215ms/step
tot index for max value:  42
namastey
./data_dir/THNB/M/param555.jpg
1/1 [==============================] - 0s 375ms/step
tot index for max value:  10
M
./data_dir/THNB/proof/shruti135.jpg
1/1 [==============================] - 0s 212ms/step
tot index for max value:  43
proof
./data_dir/THNB/R/param295.jpg
1/1 [==============================] - 0s 237ms/step
tot index for max value:  14
R
./data_dir/THNB/signature/shruti435.jpg
1/1 [==============================] - 0s 211ms/step
tot index for max value:  45
signature
./data_dir/THNB/dog/285 (3).png
1/1 [==============================] - 0s 216ms/step
tot index for max value:  49
tiger
./data_dir/THNB/jeans/soumya95.jpg
1/1 [==============================] - 0s 208ms/step
tot index for max value:  36
jeans
./data_dir/THNB/E/jbj80.jpg
1/1 [==============================] - 0s 368ms/step
tot index for max value:  3
E
./data_dir/THNB/meet/drturuk38

1/1 [==============================] - 2s 2s/step


ValueError: ignored

In [ ]:
from PIL import Image
def ensemble_predictions(members, testX):
  individual_pred=[]
  tot=[]
 # make predictions
  for model in members:
    model_curr=model.predict(testX)
    preds=list(model_curr[0])

    if members.index(model)==0:
      # tot+=model_curr[0][0]
      tot= model_curr[0][0]
      # print("for google net",tot)
      #max(max(prediction[0])))
        


    else:
      tot=list(map(add, tot, preds))
      # print("other models",tot)

    # preds=list(model_curr[0])
    # print(preds)
    # print(max(preds))
    # individual_pred.append(preds.index(max(preds)))
  max_val=max(tot)  
  # print("max len: ",max_val)
  # print("len: ",len(tot))
  print("tot index for max value: ",tot.index(max_val))
  # individual_pred=np.array(individual_pred)
  # summed = np.sum(individual_pred, axis=0)
  # print(individual_pred)
  # argmax across classes
  result = enumList[tot.index(max_val)]
  return result





ipf = "./data_dir/THNB"
acc=0
l_final=[]
for classes in os.listdir(ipf):
  folderpath = os.path.join(ipf,classes)
  files=os.listdir(folderpath)
  d=random.choice(files)

# img_path = "/content/data_dir/split/test/D/agrima130.jpg"
# # img = image.load_img(img_path, target_size=(224, 224,3))
# img2 = cv2.imread(img_path)
# resized = cv2.resize(img2,(224,224))
# testdata1=np.array(resized)
# # testdata1 = testdata1.astype('float32')
# testdata1= np.reshape(testdata1,[1,224,224,3] )
  # print("files",files)
  img_path = os.path.join(folderpath,d)
  print(img_path)
  # img = Image.load_img(img_path, target_size=(224, 224,3))
  img2 = cv2.imread(img_path)
  resized = cv2.resize(img2,(224,224))
  testdata1=np.array(resized)
# testdata1 = testdata1.astype('float32')
  testdata1= np.reshape(testdata1,[1,224,224,3] )
  out = ensemble_predictions(members,testdata1)
  if classes==out:
    acc+=1
    l_final.append(out)

  else:
    l_final.append('wrong class classified: {}'.format(classes))  


  print(out)
print(l_final)
print(acc)

./data_dir/THNB/namastey/rajesh480.jpg
1/1 [==============================] - 0s 204ms/step
tot index for max value:  42
namastey
./data_dir/THNB/M/avdhoot390.jpg
1/1 [==============================] - 0s 197ms/step
tot index for max value:  10
M
./data_dir/THNB/proof/soumya130.jpg
1/1 [==============================] - 0s 197ms/step
tot index for max value:  40
meet
./data_dir/THNB/R/soumya2480.jpg
1/1 [==============================] - 0s 208ms/step
tot index for max value:  10
M
./data_dir/THNB/signature/soumya310.jpg
1/1 [==============================] - 0s 204ms/step
tot index for max value:  40
meet
./data_dir/THNB/dog/465 (3).png
1/1 [==============================] - 0s 361ms/step
tot index for max value:  49
tiger
./data_dir/THNB/jeans/shruti235.jpg
1/1 [==============================] - 0s 193ms/step
tot index for max value:  36
jeans
./data_dir/THNB/E/jbj315.jpg
1/1 [==============================] - 0s 201ms/step
tot index for max value:  3
E
./data_dir/THNB/meet/rajesh510

In [ ]:
from PIL import Image
def ensemble_predictions(members, testX):
  individual_pred=[]
  tot=[]
 # make predictions
  for model in members:
    model_curr=model.predict(testX)
    preds=list(model_curr[0])

    if members.index(model)==0:
      # tot+=model_curr[0][0]
      tot= model_curr[0][0]
      # print("for google net",tot)
      #max(max(prediction[0])))
        


    else:
      tot=list(map(add, tot, preds))
      # print("other models",tot)

    # preds=list(model_curr[0])
    # print(preds)
    # print(max(preds))
    # individual_pred.append(preds.index(max(preds)))
  max_val=max(tot)  
  # print("max len: ",max_val)
  # print("len: ",len(tot))
  print("tot index for max value: ",tot.index(max_val))
  # individual_pred=np.array(individual_pred)
  # summed = np.sum(individual_pred, axis=0)
  # print(individual_pred)
  # argmax across classes
  result = enumList[tot.index(max_val)]
  return result





ipf = "./data_dir/THNB"
acc=0
l_final=[]
for classes in os.listdir(ipf):
  folderpath = os.path.join(ipf,classes)
  files=os.listdir(folderpath)
  d=random.choice(files)

# img_path = "/content/data_dir/split/test/D/agrima130.jpg"
# # img = image.load_img(img_path, target_size=(224, 224,3))
# img2 = cv2.imread(img_path)
# resized = cv2.resize(img2,(224,224))
# testdata1=np.array(resized)
# # testdata1 = testdata1.astype('float32')
# testdata1= np.reshape(testdata1,[1,224,224,3] )
  # print("files",files)
  img_path = os.path.join(folderpath,d)
  print(img_path)
  # img = Image.load_img(img_path, target_size=(224, 224,3))
  img2 = cv2.imread(img_path)
  resized = cv2.resize(img2,(224,224))
  testdata1=np.array(resized)
# testdata1 = testdata1.astype('float32')
  testdata1= np.reshape(testdata1,[1,224,224,3] )
  out = ensemble_predictions(members,testdata1)
  if classes==out:
    acc+=1
    l_final.append(out)

  else:
    l_final.append('wrong class classified: {}'.format(classes))  


  print(out)
print(l_final)
print(acc)

./data_dir/THNB/namastey/rajesh105.jpg
1/1 [==============================] - 0s 205ms/step
tot index for max value:  42
namastey
./data_dir/THNB/M/soumya515.jpg
1/1 [==============================] - 0s 355ms/step
tot index for max value:  10
M
./data_dir/THNB/proof/shruti130.jpg
1/1 [==============================] - 0s 199ms/step
tot index for max value:  43
proof
./data_dir/THNB/R/avdhoot140.jpg
1/1 [==============================] - 0s 197ms/step
tot index for max value:  10
M
./data_dir/THNB/signature/shruti285.jpg
1/1 [==============================] - 0s 216ms/step
tot index for max value:  45
signature
./data_dir/THNB/dog/465 (3).png
1/1 [==============================] - 0s 228ms/step
tot index for max value:  49
tiger
./data_dir/THNB/jeans/shruti255.jpg
1/1 [==============================] - 0s 206ms/step
tot index for max value:  36
jeans
./data_dir/THNB/E/agrima240.jpg
1/1 [==============================] - 0s 373ms/step
tot index for max value:  3
E
./data_dir/THNB/meet/d

In [ ]:
def ensemble_predictions(members, testX):
 # make predictions
 yhats = [model.predict(testX) for model in members]
 yhats = np.array(yhats)
 # sum across ensemble members
 summed = np.sum(yhats, axis=0)
 # argmax across classes
 result = np.argmax(summed, axis=1)
 return result

In [ ]:
ensemble_predictions(members,testdata1)

1/1 [==============================] - 0s 27ms/step


array([33])

In [ ]:
img_path = "/content/data_dir/THNB/A/agrima105.jpg"
# img = image.load_img(img_path, target_size=(224, 224,3))
img2 = cv2.imread(img_path)
resized = cv2.resize(img2,(224,224))
testdata1=np.array(resized)
# testdata1 = testdata1.astype('float32')
testdata1= np.reshape(testdata1,[1,224,224,3] )
# np.expand_dims(testdata1, axis=0)
# img_array = image.img_to_array(img)
# img_batch = np.expand_dims(img_array, axis=0)
# img_preprocessed = preprocess_input(img_batch)
prediction = model_2.predict(testdata1)
# prediction[0]
print(max(list(prediction[1])))



1/1 [==============================] - 0s 28ms/step


IndexError: ignored

#One Image Multiple Models

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as pl


img_path = "/content/data_dir/cluster2/OHNB/deer/10.png"
img2 = cv2.imread(img_path)
resized = cv2.resize(img2,(224,224))
testdata1=np.array(resized)
testdata1= np.reshape(testdata1,[1,224,224,3] )

prediction = model_1.predict(testdata1)
prediction[0]

1/1 [==============================] - 8s 8s/step


array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.0140788e-07, 0.0000000e+00,
        0.0000000e+00, 9.9999964e-01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as pl


img_path = "/content/data_dir/cluster2/OHNB/deer/10.png"
img2 = cv2.imread(img_path)
resized = cv2.resize(img2,(224,224))
testdata1=np.array(resized)
testdata1= np.reshape(testdata1,[1,224,224,3] )

prediction = model_2.predict(testdata1)
prediction[0]

1/1 [==============================] - 1s 692ms/step


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as pl


img_path = "/content/data_dir/cluster2/OHNB/deer/10.png"
img2 = cv2.imread(img_path)
resized = cv2.resize(img2,(224,224))
testdata1=np.array(resized)
testdata1= np.reshape(testdata1,[1,224,224,3] )

prediction = model_3.predict(testdata1)
prediction[0]

1/1 [==============================] - 1s 545ms/step


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]],
      dtype=float32)

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as pl


img_path = "/content/data_dir/cluster2/OHNB/deer/10.png"
img2 = cv2.imread(img_path)
resized = cv2.resize(img2,(224,224))
testdata1=np.array(resized)
testdata1= np.reshape(testdata1,[1,224,224,3] )

prediction = model_4.predict(testdata1)
prediction[0]

1/1 [==============================] - 1s 569ms/step


array([[0.0000000e+00, 8.0824886e-28, 8.3249737e-28, 2.4754034e-21,
        0.0000000e+00, 3.9020433e-29, 1.0000000e+00, 0.0000000e+00]],
      dtype=float32)

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as pl


img_path = "/content/data_dir/cluster2/OHNB/deer/10.png"
img2 = cv2.imread(img_path)
resized = cv2.resize(img2,(224,224))
testdata1=np.array(resized)
testdata1= np.reshape(testdata1,[1,224,224,3] )

prediction = model_5.predict(testdata1)
prediction[0]

1/1 [==============================] - 1s 526ms/step


array([[0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as pl


img_path = "/content/data_dir/cluster2/OHNB/deer/10.png"
img2 = cv2.imread(img_path)
resized = cv2.resize(img2,(224,224))
testdata1=np.array(resized)
testdata1= np.reshape(testdata1,[1,224,224,3] )

prediction = model_6.predict(testdata1)
prediction[0]

1/1 [==============================] - 1s 898ms/step


array([2.1504058e-05, 5.1953232e-01, 1.5535045e-03, 4.5613931e-03,
       3.5367411e-05, 1.6656326e-04, 1.7769738e-04, 4.8777733e-06,
       2.0950081e-05, 9.0902381e-07, 4.6184078e-01, 1.2035347e-02,
       4.8586619e-05, 2.5186193e-07, 2.1452347e-08], dtype=float32)

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as pl


img_path = "/content/data_dir/cluster2/OHNB/deer/10.png"
img2 = cv2.imread(img_path)
resized = cv2.resize(img2,(224,224))
testdata1=np.array(resized)
testdata1= np.reshape(testdata1,[1,224,224,3] )

prediction = model_7.predict(testdata1)
prediction[0]

1/1 [==============================] - 0s 143ms/step


array([2.1877278e-05, 3.4680820e-04, 2.0260112e-03, 2.6014617e-05,
       2.6401004e-04, 1.4751589e-04, 8.8733032e-05, 4.2750868e-05,
       3.9499238e-04, 5.4593821e-04, 1.0525667e-08, 3.4707023e-07,
       4.4031742e-10, 1.2746452e-09, 1.2316147e-09, 1.2017721e-03,
       1.4737947e-08, 8.4021091e-01, 1.2597406e-08, 1.5467630e-01,
       1.6938178e-09, 5.8700011e-06, 1.7062607e-11], dtype=float32)

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as pl


img_path = "/content/data_dir/cluster2/OHNB/deer/10.png"
img2 = cv2.imread(img_path)
resized = cv2.resize(img2,(224,224))
testdata1=np.array(resized)
testdata1= np.reshape(testdata1,[1,224,224,3] )

prediction = model_8.predict(testdata1)
prediction[0]

1/1 [==============================] - 0s 224ms/step


array([1.6485283e-05, 1.2774076e-04, 2.0837016e-01, 7.9142416e-01,
       1.1516991e-05, 3.2163782e-05, 1.7465429e-05, 2.9240721e-07],
      dtype=float32)

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as pl


img_path = "/content/data_dir/cluster2/OHNB/deer/10.png"
img2 = cv2.imread(img_path)
resized = cv2.resize(img2,(224,224))
testdata1=np.array(resized)
testdata1= np.reshape(testdata1,[1,224,224,3] )

prediction = model_9.predict(testdata1)
prediction[0]

1/1 [==============================] - 0s 211ms/step


array([1.0317136e-04, 9.6059091e-02, 1.5903379e-05, 8.7451577e-02,
       4.4538076e-03, 8.1190783e-01, 8.6000528e-06], dtype=float32)

In [ ]:
# import numpy as np
# import cv2
# import matplotlib.pyplot as pl


# img_path = "/content/data_dir/cluster2/OHNB/deer/10.png"
# img2 = cv2.imread(img_path)
# resized = cv2.resize(img2,(224,224))
# testdata1=np.array(resized)
# testdata1= np.reshape(testdata1,[1,224,224,3] )

# prediction = model_1.predict(testdata1)
# prediction[0]

In [ ]:
prediction = model_1.predict(testdata1)
print("************Googlenet*******")
print(prediction[0])
print(max(max(prediction[0])))
# print(prediction[0].shape())
prediction1 = model_2.predict(testdata1)
print("************Alexnet*******")
print(prediction1[0])
print(max(list(prediction1[0])))
prediction2 = model_4.predict(testdata1)
print("************Vgg19net*******")
print(prediction2[0])
print(max(list(prediction2[0])))
prediction3 = model_5.predict(testdata1)
print("************Resnet*******")
print(prediction3[0])
print(max(list(prediction3[0])))

1/1 [==============================] - 0s 25ms/step
************Googlenet*******
[[8.20503283e-06 4.92355684e-06 1.95777484e-05 2.64299615e-06
  5.25745127e-05 6.41219376e-05 2.77518790e-04 1.14500690e-05
  2.63947368e-05 4.82318166e-04 5.61775123e-05 1.00323618e-04
  6.43999738e-05 2.25239037e-05 1.52005698e-04 3.15124726e-06
  1.68810366e-05 5.93492587e-04 6.62272896e-06 6.14152350e-06
  2.25020358e-06 1.23138365e-04 7.46211881e-05 5.22857081e-05
  1.08662272e-04 3.56712990e-05 6.98151474e-04 1.37507811e-03
  2.81127188e-02 4.57564718e-04 1.16530246e-04 4.72702914e-06
  2.31398037e-04 8.44275201e-06 3.04712839e-02 3.37245160e-06
  7.90398008e-06 3.92318798e-05 1.08600261e-05 3.83754123e-05
  4.37048475e-05 4.71600652e-04 3.22599575e-04 5.28334886e-06
  2.79964788e-05 1.04946857e-05 5.91607386e-05 4.05458695e-06
  1.73874050e-05 9.34974611e-01 1.06069765e-05 1.08770517e-04]]
0.9349746
1/1 [==============================] - 0s 20ms/step
************Alexnet*******
[0.01312335 0.0176746 